# MySQL Properties
server.port=${PORT:9090}
spring.datasource.url=${SPRING_DATASOURCE_AIVEN_URL}
spring.datasource.username=${SPRING_DATASOURCE_AIVEN_USERNAME}
#enter the correct MySQL Password below
spring.datasource.password=${SPRING_DATASOURCE_AIVEN_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#//FOR CREATING TABLE AND SCHEMA 
spring.jpa.hibernate.ddl-auto=update

#THis tells project jpa kis language ko smghega ya kis lan. me kam kr payega
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.packagesToScan=com.etohfa.controller
springdoc.pathsToMatch=/api/**

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# need to remove this 
spring.devtools.restart.enabled=false

# cloudinary creds
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}